### PR TITLE
Fix assay bug in the upstream-analysis

### LINKED ISSUE #121: Fix assay bug in the upstream-analysis
## What analysis module should be updated and why?

To fix a bug related to which assay to select when filtering the final object as discussed previously with @sharonfreshour.

### Which areas should receive a particularly close look?

- [x] So that you know, an error might occur if too many features are removed from the matrix. for your reference, I get the following:

```
> DefaultAssay(seurat_obj) <- "RNA_SoupX"
> print(table(seurat_obj@meta.data$ID))

DST800 DST802 DST804 DST809 DST811 DST813 DST815 DST817 
   889    703    858    926    954    983    809    950 
```

And this leads to the following error:

```
Error in `PrepDR()`:
! Variable features haven't been set. Run FindVariableFeatures() or provide a vector of feature names.
Backtrace:
  1. rmarkdown::render(...)
  2. rmarkdown::render(...)
  3. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  4. knitr:::process_file(text, output)
  7. knitr:::process_group(group)
     ...
 15. base::withRestarts(...)
 16. base (local) withRestartList(expr, restarts)
 17. base (local) withOneRestart(withRestartList(expr, restarts[-nr]), restarts[[nr]])
 18. base (local) docall(restart$handler, restartArgs)
 20. evaluate (local) fun(base::quote(`<smplErrr>`))

Quitting from lines 383-388 [process-seurat] (04_run_filter_object.Rmd)
                                                                                                                             
Execution halted
```

### PR DESCRIPTION
**Pull request by AntoniaChroni**
# Purpose/implementation Section

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## What scientific question/module of analysis is your analysis addressing?

To fix a bug related to which assay to select when filtering the final object.

## What GitHub issue does your pull request address?

Closes #121.

## Directions for reviewers 
Tell potential reviewers what kind of feedback you are soliciting.

- [x] Please review for code logic and clarity.

### Which areas should receive a particularly close look?

- [x] Run only the code for filtering the object by including SoupX matrix, i.e., `04_run_filter_object.Rmd` and `05_run_summary_report.Rmd` scripts. 
- [x] Number of cells decreases when including SoupX matrix (For more information see #121). This shouldn't happen. Please confirm how the matrix looks like on your end.

## Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.

## Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

File: analyses/upstream-analysis/run-upstream-analysis.R [hunk 1]
```diff
@@ -29,53 +29,54 @@ Final_summary_report_dir <- file.path(analysis_dir, "plots", "05_Final_summary_r
...
-                    LEAD_ANALYSTS = yaml$LEAD_ANALYSTS,
-                    GROUP_LEAD = yaml$GROUP_LEAD,
-                    CONTACT_EMAIL = yaml$CONTACT_EMAIL,
-                    PIPELINE = yaml$PIPELINE, 
-                    START_DATE = yaml$START_DATE,
-                    COMPLETION_DATE = yaml$COMPLETION_DATE))
+# rmarkdown::render('02_run_SoupX.Rmd', 
+#                   clean = FALSE,
+#                   output_dir = file.path(SoupX_dir),
+#                   output_dir = file.path(SoupX_dir),
```
Comment (sharonfreshour) [inline analyses/upstream-analysis/run-upstream-analysis.R:39]: `output_dir` parameter is duplicated

```suggestion
```

**Review by sharonfreshour — APPROVED** [review]
Code looks clear and seems logical. 

The test run completed successfully with specifying `assay_filter_object: "RNA_SoupX"` in the yaml. I did not get the `PrepDR()` error that was previously reported.

The reports generated for the run do show that `seurat_obj` has the incorrect number of cells remaining from each sample after the SoupX correction (screenshot attached), as discussed in issue https://github.com/stjude-dnb-binfcore/sc-rna-seq-snap/issues/121.

Screenshot 2025-01-13 at 11 48 20 AM

I am approving this PR since the assay bug appears to be fixed and the run completes successfully, regardless of the cell count issue.

**Comment by AntoniaChroni** [comment]
Per our conversation with @sharonfreshour, she figured out the bug when including the SoupX matrix in the final filtering step, great job! 🙌 

I updated the scripts accordingly. She tested the final code. The bug was due to the following issue:


- The issue with the cell numbers is related to a typo in `02_run_SoupX.Rmd` that causes most of the cell names (i.e. column names) to be incorrect in SoupX_corrected_mtx_merged.rds. 

 ```
Line 263 in 02_run_SoupX.Rmd currently has this line of code:
colnames(out) <- paste0(sample_name, ":", colnames(out)), but it should be colnames(out) <- paste0(sample_name[i], ":", colnames(out)).
 ```

Because most of the column names are incorrect, when `SoupX_corrected_mtx_merged.rds` is loaded and it's column names are compared to seurat_obj column names in `04_run_filter_object.Rmd` to subset `seurat_obj`, most of the cells get removed from `seurat_obj`. The table in issue #121 is showing the number of cells that don't get removed.
