### PR TITLE
Fix bug with colors in the integration module

### LINKED ISSUE #246: Updated analysis: Fix bug with colors in the integration module
## What analysis module should be updated and why?

The `integrative-analysis` module currently has a limitation when using `scale_fill_brewer(palette = "Set2")`, as the palette supports a fixed number of colors, i,e., 8. 

When the number of samples exceeds the size of the Set2 palette, this introduces a bug where some samples are left without an assigned color due to the palette’s fixed number of available colors.

We will update this step to extract the color mapping from the DimPlot and apply the same colors to the fraction-of-cells plot for visual consistency.

### PR DESCRIPTION
**Pull request by AntoniaChroni**
# Purpose/implementation Section

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## What scientific question/module of analysis is your analysis addressing?

The `integrative-analysis` module currently has a limitation when using `scale_fill_brewer(palette = "Set2")`, as the palette supports a fixed number of colors, i,e., 8. 

When the number of samples exceeds the size of the Set2 palette, this introduces a bug where some samples are left without an assigned color due to the palette’s fixed number of available colors.

We will update this step to extract the color mapping from the DimPlot and apply the same colors to the fraction-of-cells plot for visual consistency.

## What GitHub issue does your pull request address?

Closes #246.

## Directions for reviewers 
Tell potential reviewers what kind of feedback you are soliciting.

### Which areas should receive a particularly close look?

Please review the code for logic and clarity, and test with a dataset with more than 8 samples.

## Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.

## Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Comment by AntoniaChroni** [comment]
@sharonfreshour, I noticed that the plotting variable is hardcoded to `orig.ident`, which can cause issues in the plots if a different column is used for integration. Fixed here 4374d58d68ecc8490d7dd6fb9b65bb47a9897aa5.

**Review by sharonfreshour — COMMENTED** [review]
The module runs successfully and generates colors for all samples in proportion plots. Overall, the code appears to be clear and logical. 

However, the script to rerun integration after removing clusters in the `cell-contamination-removal-analysis` should be updated with the same bug fix as well (i.e. `analyses/cell-contamination-removal-analysis/02-integrative-analysis.Rmd`).

Also, for updating the plotting variable to not be hard coded, I think it would make sense to include the updates to `custom-seurat-functions.R‎` to also remove the hard coding of `orig.ident` there as well, so the `Before vs After integration plots` display the UMAPs and proportion plots using the integration variable. If you think it is important to always show the `Before vs After integration plot` UMAPs and proportion plots with `orig.ident`, perhaps you could include two versions for these plots. One which always shows the `orig.ident` UMAPs and proportion plots and one which shows the plots for the integration variable. While this might be redundant when `ID` is used as the variable, I think it would be useful information to have when different integration variables are used. However, as the module runs successfully currently, this is just something to consider.

**Comment by AntoniaChroni** [comment]
> The module runs successfully and generates colors for all samples in proportion plots. Overall, the code appears to be clear and logical.
> 
> However, the script to rerun integration after removing clusters in the `cell-contamination-removal-analysis` should be updated with the same bug fix as well (i.e. `analyses/cell-contamination-removal-analysis/02-integrative-analysis.Rmd`).
> 
> Also, for updating the plotting variable to not be hard coded, I think it would make sense to include the updates to `custom-seurat-functions.R‎` to also remove the hard coding of `orig.ident` there as well, so the `Before vs After integration plots` display the UMAPs and proportion plots using the integration variable. If you think it is important to always show the `Before vs After integration plot` UMAPs and proportion plots with `orig.ident`, perhaps you could include two versions for these plots. One which always shows the `orig.ident` UMAPs and proportion plots and one which shows the plots for the integration variable. While this might be redundant when `ID` is used as the variable, I think it would be useful information to have when different integration variables are used. However, as the module runs successfully currently, this is just something to consider.

All done! I thought I had passed the changes everywhere, but alas, I had not. Fixed here: 85e90a9531bbb6b15e1fc592de1327d4d1303b5b.

File: analyses/integrative-analysis/util/custom-seurat-functions.R [hunk 1]
```diff
@@ -1,21 +1,23 @@
...
 #'
 #' @examples
 #' 
-plot_integrated_clusters = function (seurat_obj) { 
-  ## take an integrated Seurat object, plot distributions over orig.ident
+plot_integrated_clusters = function (seurat_obj, palette, variable_value) { 
+  ## take an integrated Seurat object, plot distributions over the specified variable
   
-  count_table <- table(seurat_obj@meta.data$seurat_clusters, seurat_obj@meta.data$orig.ident)
+  count_table <- table(seurat_obj@meta.data$seurat_clusters, seurat_obj@meta.data$variable_value)
```
Comment (sharonfreshour) [inline analyses/integrative-analysis/util/custom-seurat-functions.R]:
```suggestion
  count_table <- table(seurat_obj@meta.data$seurat_clusters, seurat_obj@meta.data[[variable_value]])
```

The format to get the `variable_value` column needs to be updated to correctly get the column data, otherwise it'll cause an error.

**Review by sharonfreshour — APPROVED** [review]
The updates to the code appear to be clear and logical. However, the format for calling the `variable_value` column in the `custom-seurat-functions.R‎` does need to be updated to run successfully (see suggestion on the script). Since this is a small change to the code and I tested to confirm the runs successfully with this change, I will approve.

File: analyses/integrative-analysis/util/custom-seurat-functions.R (hunk 1 above)
Comment (AntoniaChroni) [reply analyses/integrative-analysis/util/custom-seurat-functions.R]: Ugh.. fixed here: 9e2d4bf8152b137d9a09fc6be265e93d203bb500.
