### PR TITLE
Fix bug condition3

### LINKED ISSUE #167: Updated analysis: fix-bug-filtering-with-doublets-condition3
## What analysis module should be updated and why?

There is a bug in the `04_run_filter_object.Rmd` script related to the filtering of doublets. This issue prevents some metadata from being properly transferred to the new object. As a result, the data for `condition3` in one of my cohorts was not plotted, because the corresponding column was missing from the metadata."

### PR DESCRIPTION
**Pull request by AntoniaChroni**
# Purpose/implementation Section

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## What scientific question/module of analysis is your analysis addressing?

There is a bug in the 04_run_filter_object.Rmd script related to the filtering of doublets. This issue prevents some metadata from being properly transferred to the new object. As a result, the data for `condition3` in one of my cohorts was not plotted, because the corresponding column was missing from the metadata."

## What GitHub issue does your pull request address?

Closes #167.

## Directions for reviewers 
Tell potential reviewers what kind of feedback you are soliciting.

### Which areas should receive a particularly close look?
 
Please review for code logic and clarity. Also, test one cohort for the suggested code changes to confirm updates are being properly displayed.

## Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.

## Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

File: analyses/upstream-analysis/util/function-process-Seurat.R [hunk 1]
```diff
@@ -381,7 +381,7 @@ Process_Seurat <- function(seurat_obj, nfeatures_value, Genome, Regress_Cell_Cyc
```
Comment (sharonfreshour) [inline analyses/upstream-analysis/util/function-process-Seurat.R:381]: I noticed that for plots `06`, `07`, and `08` the `.png` files are being saved as `pdf`. This doesn't impact how they are displayed in the `04_run_filter_object` report since they are printed into the report, but it does impact the saved plots. It causes them to be corrupted and unable to be opened, which will mean they wouldn't be displayed for the reports from the `05_run_summary_report.Rmd` script.

Lines `378-380`, `388-390`, and `399-401` should be replaced by a `ggsave()` command similar to the other `png` plots.

**Review by sharonfreshour — APPROVED** [review]
Code for bug fixes appear to be clear and logical. Test run completed successfully and all three conditions display correctly in the report when doublet filtering is used, there are no duplicates in the metadata, and the figure numbers are updated.

I noticed a bug related to how some png figures are being saved in the `function-process-Seurat.R` script and left specific comments on the script.

I am still approving since this bug is not directly related to the specific bug being addressed in the this PR.

File: analyses/upstream-analysis/util/function-process-Seurat.R (hunk 1 above)
Comment (AntoniaChroni) [reply analyses/upstream-analysis/util/function-process-Seurat.R:380]: Great catch, thank you! This is now fixed and tested here: 53ad88a353838023a790ff1e5fd483e22813a346.
