### PR TITLE
Fix dual genome mtdna

### LINKED ISSUE #238: Bug: `02A_run_seurat_qc.Rmd` does not properly calculate mitochondrial gene expression % for dual genome alignments
## What analysis module should be updated and why?
Module: `upstream-analysis`
Script: `02A_run_seurat_qc.Rmd`
Genome: `GRCh38ANDGRCm39` (but this bug is relevant for all dual genome references).
Test cohort: Rainbow scRNAseq (this data will be shared with @AntoniaChroni)

This bug does not cause an error or prevent the module from running. However, when examining the violin plots in the reports for the `02_Seurat_qc` and `05_Final_summary_report` steps of the module, all samples for dual genome alignment runs will show 0% mitochondrial expression. 

This bug appears to be related to the way mitochondrial expression is calculated in the `create_seurat_obj()` function (called on line `268` in the `02A_run_seurat_qc.Rmd` script) from the `scooter` package. 

This is the code used in that function, found [here](https://github.com/igordot/scooter/blob/master/R/import.R):
```
  # get all mitochondrial genes (may fail depending on species or annotation)
  mt_genes <- grep("^MT-", rownames(s_obj@assays$RNA@counts),
    ignore.case = TRUE, value = TRUE
  )
```

The code does not appear to be capable of handling the genome prefixes (e.g. `GRCh38-`, `GRCm39-`) that are appended to gene names when `cellranger` alignment is run with a dual genome.

### PR DESCRIPTION
**Pull request by AntoniaChroni**
# Purpose/implementation Section

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Mitochondrial Gene Detection Across Genome Formats

The original 'calculate_mito_pct' helper function from the [scooter package](https://github.com/igordot/scooter/blob/master/R/import.R) only detects mitochondrial genes in single-genome settings and assumes standard gene symbols such as:

      - Human: MT-CO1, MT-ND1
      - Mouse: mt-Nd1, mt-Co1

However, our pipeline supports multiple genome configurations, including:
 
     - Human (GRCh38, hg19)
      - Mouse (GRCm39, mm10, mm9)
      - Dual genomes (e.g., GRCh38 + mm10), which can contain *both* MT- and mt- prefixes
      - Custom references with additional prefixes (e.g., GRCm39-mt-Nd5, Prefix-mt-Co2)

To ensure full compatibility across all supported genome reference formats, we introduce an updated function, `calculate_mito_pct_updated()`, which:
 1. Uses a generalized mitochondrial gene pattern that matches:
      - Human-style:   MT-*
      - Mouse-style:   mt-*
      - Prefixed:      <anything>-mt-*
2. Correctly identifies mitochondrial features in single or dual genomes.
3. Computes percent mtDNA reads per cell and stores the result in metadata.

This update ensures that mitochondrial QC metrics are calculated reliably regardless of annotation source, species, genome build, or custom reference structure.

## What GitHub issue does your pull request address?

Closes #238.

## Directions for reviewers 
Tell potential reviewers what kind of feedback you are soliciting.

### Which areas should receive a particularly close look?

- [x] Please review the code and documentation logic.
- [x] Test by using the [sc-rna-seq-snap-Rainbow-scRNAseq-all](https://github.com/stjude-dnb-binfcore/sc-rna-seq-snap-Rainbow-scRNAseq-all) cohort

## Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.

## Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

File: analyses/upstream-analysis/util/import_updated.R [hunk 1]
```diff
@@ -0,0 +1,341 @@
...
+  # nGene and nUMI are automatically calculated for every object by Seurat
+  # calculate the percentage of mitochondrial genes here and store it in percent.mito using the AddMetaData
+  s_obj <- seurat_obj
+
+  # get all mitochondrial genes (may fail depending on species or annotation)
+  if (genome_name == "GRCh38" | genome_name == "hg19" | genome_name == "GRCm39" | genome_name == "mm10" | genome_name == "mm9"){
+    mt_genes <- grep("^MT-", rownames(s_obj@assays$RNA@counts),
+    ignore.case = TRUE, value = TRUE)
+    } else if (genome_name == "DualGRCh38" | genome_name == "Dualhg19" | genome_name == "DualGRCm39" | genome_name == "Dualmm10" | genome_name == "Dualmm9"){
+       mt_genes <- grep("(^mt-[A-Za-z0-9]+$)|(-mt-[A-Za-z0-9]+$)|(^MT-[A-Za-z0-9]+$)|(-MT-[A-Za-z0-9]+$)",
```
Comment (sharonfreshour) [inline analyses/upstream-analysis/util/import_updated.R:279]: For future consideration, it might be worth deteriming if there would be a need to calculate mitochondrial % based only on the mito genes from the preferred reference genome provided in the yaml file (e.g. only using genes with GRCh38-MT pattern when GRCh38 is the preferred genome) as opposed to using all mito genes across both species in a dual genome.

Asha and Cody might have more feedback on this, as I believe they have worked with more dual genome projects than I have.

**Review by sharonfreshour — APPROVED** [review]
The code and documentation appear to be clear and logical. The `02_run_seurat_qc` step runs successfully and generates non-zero values for mito%. I did leave one comment for consideration, but it does not effect the current functionality of the module. 

Approved!

File: analyses/upstream-analysis/util/import_updated.R (hunk 1 above)
Comment (AntoniaChroni) [reply analyses/upstream-analysis/util/import_updated.R:279]: Thank you for the suggestion. We would need to add an extra variable for this, and I am not sure it would be very useful in practice. I suggest we leave things as‑is for now and revisit it if there’s a concrete request for this feature.
